Sabor/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabor.Business.Abstract;
using Sabor.Entity;
using Sabor.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Sabor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IProductServices _productServices;
        private IVideoServices _videoServices;
        private ISliderServices _sliderServices;
        public HomeController(ILogger<HomeController> logger, IProductServices productServices, IVideoServices videoServices, ISliderServices sliderServices)
        {
            _logger = logger;
            _productServices = productServices;
            _videoServices = videoServices;
            _sliderServices = sliderServices;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Productses(string category,int pages=1) //buraya page değeri routeden geliyor
        {
            const int pageSize = 1;
            ProductsListViewModel productsListViewModel = new ProductsListViewModel()
            {
                pageInfo = new PageInfo()
                {
                    TotalItems = _productServices.GetCountByCategory(category),
                    CurrentPage = pages,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productServices.GetProductByCategory(category, pages, pageSize)
            };
            return View(productsListViewModel);
        }

        public IActionResult ProductDetail(int Urunid)
        {
            Product product= _productServices.GetProductDetails(Urunid);
            return View(new ProductDetailModel {Product=product });
        }

        public IActionResult SaborTv()
        {
            return View(new VideoListViewModel {Videos=_videoServices.LastGetAll() });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sabor/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sabor.Data.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sabor.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryRepository _categoryRepository;
        public CategoriesViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"]!=null)//controllerdeki RouteDatadan categoriese gelen category değerini aldık
            
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_categoryRepository.GetAll());
        }
    }
}

Sabor/ViewComponents/PopularProductGetAllViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sabor.Data.Abstract;
using Sabor.Data.Concrate.EfCore;
using Sabor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sabor.ViewComponents
{
    public class PopularProductGetAllViewComponent:ViewComponent
    {
        private IPopularProductRepository _popularProductRepository;
        public PopularProductGetAllViewComponent(IPopularProductRepository popularProductRepository)
        {
            _popularProductRepository = popularProductRepository;
        }
        public IViewComponentResult Invoke()
        {

            return View(new PopularProductListViewModel
            {
                popularProducts = _popularProductRepository.GetAll()
            });//Sizin için seçtiklerimiz kısmı ne kadar ürün koyduysa o kadar gösterilir
        }
    }
}

Sabor/ViewComponents/ProductLastGetAllViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sabor.Business.Abstract;
using Sabor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sabor.ViewComponents
{
    public class ProductLastGetAllViewComponent:ViewComponent
    {
        private IProductServices _productServices;
        public ProductLastGetAllViewComponent(IProductServices productServices)
        {
            _productServices = productServices;
        }

        public IViewComponentResult Invoke()
        {

            return View(new ProductsListViewModel
            {
                Products = _productServices.LastProductGetAll()//son 8 ürünü getiren operasyon
            });
        }
    }
}
            

Sabor/ViewComponents/VideoOneViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sabor.Business.Abstract;
using Sabor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sabor.ViewComponents
{
    public class VideoOneViewComponent:ViewComponent
    {
        private IVideoServices _videoServices;
        public VideoOneViewComponent(IVideoServices videoServices)
        {
            _videoServices = videoServices;
        }

        public IViewComponentResult Invoke()
        {
            return View(new VideoListViewModel { Videos = _videoServices.LastOneGetAll() });
        }
    }
}

Sabor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<h1>son eklenen ürünler</h1>
@await Component.InvokeAsync("ProductLastGetAll")
<br />
<h1>Sizin için seçtiklerimiz</h1>
@await Component.InvokeAsync("PopularProductGetAll")

Sabor/Views/Home/ProductDetail.cshtml
@model ProductDetailModel

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="~/img/@Model.Product.Image" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Product.Title</h5>
        <p>@Model.Product.Description</p>
        <a href="#" class="btn btn-primary">İçerik Burası</a>
    </div>
</div>

Sabor/Views/Home/Productses.cshtml
@model ProductsListViewModel

@await Component.InvokeAsync("Categories")


@foreach (var p in Model.Products)
{
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="~/img/@p.Image" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@p.Title</h5>
            <a asp-controller="Home"
               asp-action="ProductDetail" asp-route-Urunid="@p.ProductId">İçerik</a>
        </div>
    </div>
}


<div class="row">
    <div class="col">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @for (int i = 0; i < Model.pageInfo.TotalPages(); i++)
                {
                    @if (string.IsNullOrEmpty(Model.pageInfo.CurrentCategory))//kategori dolumu boşmu
                    {
                        <li class="page-item @(Model.pageInfo.CurrentPage==i+1?"active":"")">@**o an hangi sayfa gösteriliyorsa currentpage ile bu değer gelir*@
                            @*o an hangi sayfa gösteriliyorsa o sayı i+1 e eşits
                                e aktif olsun buton değilse pasif*@     
                            <a class="page-link" href="/Sbr/Urunler?pages=@(i+1)"> @*bu değer routeye gider*@
                                @*controllerden page verilirse giderse ve zaten i+1 artacak oda eşitse buna basınca 1,2 ye gider*@
                                @(i+1) @*ekranda gösterilecek*@
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item @(Model.pageInfo.CurrentPage==i+1?"active":"")">
                            <a class="page-link" href="/Sbr/Urunler/@Model.pageInfo.CurrentCategory?pages=@(i+1)">
                                @(i+1)
                            </a>
                        </li>
                    }

                }

            </ul>
        </nav>
    </div>
</div>

Sabor/Views/Home/SaborTv.cshtml
@model VideoListViewModel
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="img/favicon.png" type="image/png">
    <link href="~/video/css/style.css" rel="stylesheet" />
    <title>Fantom Blog</title>
</head>

<body style="background: #f2f2f3">

    <section class="video-p">
        <div id="td_uid_7_5d9f731f9699b" class="tdc-row">
            <div class="vc_row td_uid_14_5d9f731f969a8_rand  wpb_row td-pb-row">
                <div class="vc_column td_uid_15_5d9f731f96d86_rand  wpb_column vc_column_container tdc-column td-pb-span12">
                    <div class="wpb_wrapper">
                        <div class="td_block_wrap td_block_video_playlist td_uid_16_5d9f731f97589_rand">
                            <div class="td_block_inner">
                                <div class="td_video_playlist_column_3">
                                    <div class="td_wrapper_video_playlist">
                                        @await Component.InvokeAsync("VideoOne")
                                        <div class="td_container_video_playlist ">
                                            <div class="td_video_controls_playlist_wrapper">
                                                <div class="td_video_stop_play_control">
                                                    <a class="td-sp-video-play td-sp td_youtube_control" onlclick="play(sbNNlZXTIfg)">
                                                    </a>
                                                </div>
                                                <div class="td_current_video_play_title_youtube td_video_title_playing">
                                                    Video Playlist

                                                </div>
                                                <div class="td_current_video_play_time_youtube td_video_time_playing">
                                                </div>
                                            </div>

                                            <div id="td_youtube_playlist_video" class="td_playlist_clickable ">

                                                @foreach (var item in Model.Videos)
                                                {
                                                    <a onclick="playSong('@item.Url')" class="@item.Url td_click_video td_click_video_youtube" data-video-id="@item.Url">
                                                        <div class="td_video_thumb"><img src="https://img.youtube.com/vi/@item.Url/default.jpg" alt="Video thumbnail"></div>
                                                        <div class="td_video_title_and_time">
                                                            <div id="@item.Url" class="td_video_title"><p>@item.Title</p></div>
                                                        </div>
                                                    </a>
                                                }


                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/video/js/script.js"></script>
</body>

</html>